name: phrase_similarity_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # or any specific version you need
  - numpy=1.21  # specific version for numpy
  - pandas=1.3  # version for pandas
  - scikit-learn=0.24  # if you're using scikit-learn
  - gensim=4.0  # for Word2Vec
  - pytest=6.2  # testing framework
  - pip  # to allow installing pip packages if needed
  - pip:
      - phrase_similarity
      - pipenv